<?php
$arr = [
    "Home",
    "About Us",
    "About",
    "Services",
    "Blog",
    "FAQ",
    "Contact",
    "Contact us",
    "Contact Us",
    "Plan",
    "Property Market",
    "Property",
    "Blogs",
    "user img",
    "Login",
    "Logout",
    "Discover More",
    "Sign up",
    "FILTER NOW",
    "Photoica",
    "No Installment",
    "THANK YOU!",
    "Copyright",
    "Installment",
    "Coming in",
    "Search Property",
    "All Rights Reserved",
    "Username",
    "Email Or Username",
    "Password",
    "Thanks a bunch for filling that out. It means a lot to us, just like you do! We really appreciate you giving us a moment of your time today. Thanks for being wi ▶",
    "Full Name",
    "N.B: If you pay in installments then you have to pay the next installments from the invest history of your dashboard",
    "Welcome To Our",
    "Phone",
    "Send Reset Passsword Link",
    "Create New Account",
    "Read More",
    "Member since",
    "Running Investment",
    "Running Invest",
    "Due Investment",
    "Completed Investment",
    "Total Investment",
    "Description",
    "Properties",
    "Share now",
    "Comments",
    "Search here",
    "Login here",
    "Blog Details",
    "Categories",
    "Location",
    "Verify Your Email Address",
    "Our Office",
    "Follow us on",
    "Remember Me",
    "Forgot password?",
    "Don't have any account? Sign Up",
    "SIGN UP FORM",
    "Sponsor By",
    "First Name",
    "Last Name",
    "Enter Your Code",
    "Email Address",
    "Didn't get Code? Click to",
    "Your Phone Number",
    "Confirm Password",
    "Resend code",
    "Previous",
    "Next",
    "Login To Your Account",
    "Already have an account? Login",
    "Please confirm your password before continuing.",
    "Forgot Your Password?",
    "Your Password",
    "Already have an account?",
    "Reset Password",
    "Enter your Email Address",
    "Don't have an account?",
    "Send Password Reset Link",
    "New Password",
    "Enter New Password",
    "Subscribe",
    "Register Here",
    "Register",
    "All Badges",
    "maintenance",
    "I Agree with the Terms & conditions",
    "Recover Password",
    "Create account",
    "403 Forbidden",
    "Forbidden",
    "You don't have permission to access ‘/’ on this server",
    "Sign Up For New Account",
    "Learn More",
    "You don’t have permission to access ‘/’ on this server.",
    "Back To Home",
    "We can't seem to find the page you are looking for",
    "Sorry page was not found!",
    "not found",
    "We're sorry, the page you requested could not be found. Please go back to the homepage or contact us at",
    "Method not allowed",
    "opps!",
    "Join Now",
    "The server encountered an internal error misconfiguration and was unable to complate your request. Please contact the server administrator.",
    "Internal Server Error",
    "Sorry, your session has expired",
    "Know More",
    "Session has expired",
    "Dashboard",
    "Feel Free To Conatct Us",
    "Bonus",
    "The affiliate program is working up to 3 refaral levels. To join to the affiliate program, you should have ac active deposit in the project.",
    "CryptoVest provide an adaptive and profitable affiliate program for long-term pertnership. You will receive referal commisiona from your pertner's deposit and a ▶",
    "Affiliate program",
    "Refer us to your friends!",
    "How it works",
    "Invest History",
    "Invest",
    "Investor Image Missing",
    "Investor",
    "Add Fund",
    "Propertys",
    "We really appreciate you giving us a moment of your time today but unfortunately the payment was unsuccessful due to') {{ session('error') ?? 'it seems some iss ▶",
    "Recent Properties",
    "Agent of Property",
    "property thumbnail",
    "Yes",
    "Payment Failed",
    "Fixed Invest",
    "Return Interval",
    "Fixed",
    "Lifetime",
    "Return For",
    "Capital back",
    "Profit Range",
    "Profit",
    "Go back to Home",
    "Loss",
    "Transaction History",
    "Details",
    "Return Time",
    "Time",
    "Opening Days",
    "Payout Information",
    "Total Installment",
    "Installment Duration",
    "Select Wallet",
    "Invest Range",
    "Available for funding",
    "Installment facility",
    "Investment Completed",
    "No installment",
    "know-more-us-image",
    "login your account",
    "Get On First Level Refferal Commission",
    "Referral Bonus Level",
    "Fund History",
    "Transaction",
    "Payout",
    "disabled",
    "Recent Blogs",
    "Payout History",
    "My Referral",
    "Referral Bonus",
    "Profile Settings",
    "Profile information",
    "Password setting",
    "identity verification",
    "address verification",
    "Support Ticket",
    "Ticket",
    "Money transfer",
    "Main Balance",
    "Interest Balance",
    "Total Deposit",
    "Total Earn",
    "Account Statistics",
    "Total Invest",
    "Invest Now",
    "Minimum Invest",
    "Minimum Deposit",
    "Minimum Earning",
    "Badges",
    "Invested",
    "Pay Installment",
    "Total Payout",
    "Total Ticket",
    "Total Referral Bonus",
    "Last Referral Bonus",
    "Latest Registered Partner",
    "The last Referral Bonus",
    "last Referral Bonus",
    "Email",
    "blog image",
    "Phone Number",
    "Preferred language",
    "Select Language",
    "Joined At",
    "Code",
    "modal dismiss",
    "for successful payment",
    "payment",
    "Pay Now",
    "Plan Name",
    "Payment By",
    "Two Factor Authenticator",
    "Enable Two Factor Authenticator",
    "Disable Two Factor Authenticator",
    "Google Authenticator",
    "DOWNLOAD APP",
    "Verify Your OTP",
    "Close",
    "Verify",
    "Pay with VoguePay",
    "Verify Your OTP to Disable",
    "Enter Google Authenticator Code",
    "Transactions",
    "Search for Transaction ID",
    "Remark",
    "Search",
    "SL No.",
    "Transaction ID",
    "Amount",
    "Remarks",
    "Invest Details",
    "Investment Details",
    "Investment Date",
    "Enter amount",
    "Type Here",
    "Your KYC submission has been pending",
    "Your KYC already verified",
    "Complete",
    "Due",
    "Confirmation",
    "Save changes",
    "Do you want to change your profile image?",
    "All Payment",
    "Complete Payment",
    "Pending Payment",
    "Cancel Payment",
    "Cancel",
    "Gateway",
    "Charge",
    "Status",
    "Search Service",
    "Subject",
    "Image Upload",
    "Upload",
    "Last Reply",
    "Reply",
    "Send Reply",
    "From date",
    "Write Message",
    "To date",
    "Related Posts",
    "Open",
    "Answered",
    "Customer Reply",
    "Closed",
    "Replied",
    "Upload File",
    "Confirm",
    "Are you want to close ticket?",
    "My Profile",
    "Open Ticket",
    "Show Ticket",
    "No Data found",
    "Email Verification",
    "Update User",
    "Update Password",
    "Admin Feedback",
    "PAYOUT NOW",
    "Payout Money",
    "Request Amount",
    "You previous request has been rejected",
    "Address Proof",
    "Select Image",
    "Charge Amount",
    "Total Payable",
    "Available Balance",
    "Additional Information To Withdraw Confirm",
    "Payment Information",
    "Transaction Limit:",
    "Change",
    "Payout history",
    "Payout By",
    "Remove",
    "Last Deposit",
    "Admin",
    "Last Withdrawal",
    "doposit user image",
    "withdrawal user image",
    "Confirm Now",
    "Please Pay",
    "To Get",
    "feature image",
    "Return Interest",
    "Received Amount",
    "Upcoming Payment",
    "Search User",
    "Pay via Monnify",
    "how it work image",
    "Bonus From",
    "Current Password",
    "Enter Current Password",
    "Address",
    "Submit",
    "Useful Links",
    "Deposit Balance",
    "2FA Security",
    "Referral Link",
    "Level",
    "bkash",
    "Upline",
    "Payment Preview",
    "PLEASE SEND EXACTLY",
    "SCAN TO SEND",
    "Warning",
    "First Log In To Your Account For Invest",
    "Your Card Information",
    "Enter your card number",
    "Enter the name on your card",
    "as your payment method",
    "saturday",
    "sunday",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "Create",
    "Create Ticket",
    "Create New Ticket",
    "Enter Subject",
    "Enter Message",
    "Action",
    "Message",
    "Return How Many Times",
    "Next Return Date",
    "Invest Status",
    "Last Return Date",
    "After All Installment completed",
    "Completed",
    "Running",
    "Property Details",
    "Active",
    "reviews",
    "review",
    "No Review Found",
    "Deactive",
    "Submit now",
    "Invest Amount",
    "Login to review",
    "Add Review",
    "Amenities",
    "Filter By Ratings",
    "Investment History",
    "Search property",
    "What are you looking for?",
    "All completed",
    "Select Location",
    "Filter By Available Funding",
    "Due Make Payment",
    "Due Installment",
    "Installment Last Date",
    "Installment Late Fee",
    "Previous Total Pay",
    "Due Amount",
    "Invest Bonus",
    "Profit Bonus",
    "Badge Bonus",
    "Bonus Type",
    "2 Step Security",
    "Use Google Authenticator to Scan the QR code  or use the code",
    "Google Authenticator is a multifactor app for mobile devices. It generates timed codes used during the 2-step verification process. To use Google Authenticator, ▶",
    "Payable",
    "Conversion Rate",
    "Active Invest",
    "Transaction Analytics",
    "Your Current Level",
    "Current Level",
    "Current Month",
    "Previous Month",
    "Total Level Bonus",
    "Level Bonus",
    "Investment Properties",
    "Share Market",
    "Send Offer",
    "My WishList",
    "WishList",
    "Bio",
    "Social Links",
    "Support ticket",
    "Google",
    "2FA",
    "Receive Offer",
    "months",
    "Money Transfer",
    "days",
    "month",
    "day",
    "years",
    "year",
    "My Properties",
    "My Shared Properties",
    "Balance Transfer",
    "Transfer",
    "Receiver Email Address",
    "Enter Password",
    "Your message",
];

return $arr;
